### ISSUE TITLE
Working on 10.15.2

### ISSUE THREAD

**Issue by vinicioslc** [johnnywolinger/ACER-F5-573G-Hackintosh#3]
Thanks for the hack every thing working,
And how you say ... wifi stop works after some time.
I will replace with some Broadcom BCM435XXX family card

**Comment by HungThinh0710** [comment]
> Thanks for the hack every thing working,
> And how you say ... wifi stop works after some time.
> I will replace with some Broadcom BCM435XXX family card

Can you say with me your cpu intel model of Acer F5-573G?

**Comment by vinicioslc** [comment]
> > Thanks for the hack every thing working,
> > And how you say ... wifi stop works after some time.
> > I will replace with some Broadcom BCM435XXX family card
> 
> Can you say with me your cpu intel model of Acer F5-573G?

Its a Intel Core i7 7500U
